# Generated by Django 5.0.3 on 2024-05-29 13:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('idRapport', models.AutoField(primary_key=True, serialize=False)),
                ('dateRapport', models.DateField()),
                ('situationReservation', models.CharField(max_length=30)),
                ('commentaire', models.TextField()),
            ],
            options={
                'db_table': 'Rapport',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('etage', models.PositiveSmallIntegerField(default=0)),
                ('zone', models.PositiveSmallIntegerField(default=1)),
                ('numero_de_salle', models.CharField(max_length=100)),
                ('nom_salle', models.CharField(max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacite', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('typeSalle', models.CharField(max_length=30)),
                ('securise', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('nomService', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('idEquipement', models.AutoField(primary_key=True, serialize=False)),
                ('nomEquipment', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TypeEquipement',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('idDemande', models.AutoField(primary_key=True, serialize=False)),
                ('DateDemande', models.DateTimeField(auto_now_add=True)),
                ('dateReservation', models.DateField(null=True)),
                ('heureDebutReservation', models.TimeField(null=True)),
                ('dureeReservation', models.DurationField(default=datetime.timedelta(seconds=3600), null=True)),
                ('nbParticipant', models.IntegerField(null=True)),
                ('typeSalleDemande', models.CharField(max_length=30, null=True)),
                ('etat_reservation', models.CharField(default='E', max_length=1)),
                ('person_demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SalleReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='API.salle')),
                ('services', models.ManyToManyField(related_name='Reservation', to='API.service')),
                ('equipments', models.ManyToManyField(related_name='demandes', to='API.typeequipement')),
            ],
            options={
                'db_table': 'Demande',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idReservation', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('commentaire', models.TextField(null=True)),
                ('reservationConcerne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.demande')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.AddField(
            model_name='salle',
            name='equiments_salle',
            field=models.ManyToManyField(related_name='salles', to='API.typeequipement'),
        ),
    ]
